### ISSUE TITLE
Rotate logs with logrotate

### ISSUE THREAD

**Issue by jhamrick** [compmodels/jupyterhub-deploy#21]
Currently, all the services we have running (docker containers, swarm, etc.) just log to the same file and never stop. We should use logrotate or something to periodically rotate the logs so they don't grow infinitely large.

**Comment by jhamrick** [comment]
This might not actually be super feasible at the moment without a lot of overhead, but maybe docker will implement something better for logging soon.

**Comment by rgbkrk** [comment]
Gosh yeah I'm hoping for something like that too. For the moment, on CoreOS it all ends up in journalctl. Not sure if it has persistence beyond that. There must be good solutions with Docker.
