### ISSUE TITLE
Update get_container in swarmspawner

### ISSUE THREAD

**Issue by jhamrick** [compmodels/jupyterhub-deploy#29]
We override get_container in swarmspawner, so this will need to be updated if jupyter/dockerspawner#20 is merged.

**Comment by minrk** [comment]
The upstream PR has been merged, but I'm not sure there actually needs to be a change here, since the method is overridden. Could it be that we should be looking up containers by id instead of name? Then it shouldn't even need an override, right?

**Comment by jhamrick** [comment]
Yeah, technically I think it doesn't _need_ to be updated, but it would be good to do it the same way that dockerspawner does it, I think.

**Comment by minrk** [comment]
ok, I was a bit worried that it might be broken if it wasn't updated. inspect_container is definitely a lot more efficient when there are many containers.
