### ISSUE TITLE
nginx config is loaded both by

### ISSUE THREAD

**Issue by minrk** [compmodels/jupyterhub-deploy#30]
when the proxy machine rebooted, an nginx instance on the proxy machine started, with incomplete config, preventing access. To fix it, I stopped the outer nginx instance before relaunching the containers:

``` bash
nginx -s stop
docker start nginx static-files
```

I believe this is because the [proxy role](https://github.com/compmodels/jupyterhub-deploy/blob/master/roles/proxy/tasks/main.yml) is putting nginx config where the outer machine will find it, and then copying it to the docker container running the 'real' nginx instance. We aren't intentionally starting the host's nginx, but I think we happen to be putting the config files where the service startup will find it on boot.

**Comment by jhamrick** [comment]
I _think_ this should just be fixed by setting the `nginx_config_dir` variable in ansible to somewhere different, and then making sure nginx isn't configured to boot on startup.
